project:
  type: website
  output-dir: docs

website:
  title: "my blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ChristelSwift
      - icon: linkedin
        href: https://www.linkedin.com/in/christellacazeswift/
format:
  html:
    theme:
      light: cosmo
      dark: solar
    css: styles.css
    highlight-style: eiffel

editor: visual

